### ISSUE TITLE
Wildfly 15 debug problems

### ISSUE THREAD

**Issue by kgoedert** [jboss-dockerfiles/wildfly#91]
Hi,

I just tried the wildfly 15 docker image with the following command:

` docker run -it -p 8080:8080 -p 8787:8787 jboss/wildfly /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 --debug`

And I am not able to do remote debugging. I tried the image for version 14 and it works. Also, trying a telnet, I get this:

```
telnet localhost 8787
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
Did I miss any configuration?

Thanks

**Comment by matheuslemke** [comment]
Where's solution? I have the same problem

**Comment by kgoedert** [comment]
My solution was to add this line on my Dockerfile

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "-c", "standalone.xml", "--debug", "*:8787"]

specifically, the last parameter.

**Comment by m4rc1no5** [comment]
If You use docker-compose.yaml then You must add *:8787 to command:
```
version: '3.3'
services:
  nurseryqueueapi:
    build:
      context: ./NurseryQueueApi
    image: nurseryqueueapi/nurseryqueueapi
    container_name: nurseryqueueapi
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug *:8787
```
